### ISSUE TITLE
Fix TypeCheckPassTast::FunctionReturnTypeValueMismatch test

### ISSUE THREAD

**Issue by atlx** [ionlang/ionir#25]
@ronthecookie:

The test `FunctionReturnTypeValueMismatch` under the suite `TypeCheckPassTast` located on [`test/passes/type_check_pass.cpp`](https://github.com/ionlang/ionir/blob/master/test/passes/type_check_pass.cpp#L64) is broken.

The issue is that it's expecting an exception to be thrown, but with the updated API, now the error is collected under `passContext::diagnostics`.

---
1. Remove the `EXPECT_THROW` assertion.
2. Ensure that a diagnostic exists on `passContext->diagnostics` (size is 1).
3. Use an assertion to compare this diagnostic with the corresponding diagnostic template under [`diagnostic.h`](https://github.com/ionlang/ionir/blob/master/include/ionir/diagnostics/diagnostic.h).¹

¹ _Take a look [at this test's code](https://github.com/ionlang/ionir/blob/master/test/passes/type_check_pass.cpp#L43) to guide you on how to make the comparison._

**Comment by TorchedSammy** [comment]
if the pull request related to this issue is merged, this should be closed

**Comment by atlx** [comment]
@TorchedSammy Thanks for that note. On the pull request that @ronthecookie made, he added the `fixes` keyword which is used internally by GitHub to automatically close issues once the commit is merged onto the _default_ branch. In other words, once this patch is merged with `master` branch, this issue will automatically close.

**Comment by TorchedSammy** [comment]
ohhh it didn't get merged to master, okay I see
